/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// dotprod_comb_112
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78002/CNN --prefix dotprod_comb_112 --checkpoint-file trained/dot_emb_112_checkpoint-q.pth.tar --config-file networks/dotprod.yaml --overwrite --start-layer 73 --weight-start 2000 --device MAX78002 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 74 layers
// Input data: HWC
// Layer 73: 64x1x1, no pooling, linear, no activation, 1024x1x1 output

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "max78000_video_cnn.h"
#include "max78000_video_cnn_3.h"
#include "max78000_video_weights_3.h"

#define S_MODULE_NAME "cnn_3"
volatile uint32_t cnn_3_time; // Stopwatch
void CNN_3_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_3_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

static const uint32_t kernels_3[] = KERNELS_3;

static uint8_t mexpress_byte(const uint32_t **addr, uint32_t *val, int *avail)
{
  if (*avail == 0) {
    *val = *(*addr)++;
    *avail = 4;
  }

  return (*val >> (--(*avail) * 8)) & 0xff;
}

int cnn_verify_weights(void)
{
  uint32_t len, data, val;
  volatile uint32_t *addr, *ptr;
  const uint32_t *compare = kernels_3;
  int av;

  while ((addr = (volatile uint32_t *) *compare++) != 0) {
    len = (*compare++ * 4) / 9;
    ptr = (volatile uint32_t *)(((uint32_t)addr & 0xffffe000) | (((uint32_t)addr & 0x1fff) << 2));
    av = 0;
    val = 0;

    while (len-- > 0) {
      data = mexpress_byte(&compare, &val, &av);
      printf("Addr[0]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
      ptr++;
      /*if (*ptr++ != data) {
        printf("Addr[0]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
      data = mexpress_byte(&compare, &val, &av) << 24 | mexpress_byte(&compare, &val, &av) << 16
           | mexpress_byte(&compare, &val, &av) << 8 | mexpress_byte(&compare, &val, &av);
      printf("Addr[1]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
      ptr++;     
      /*if (*ptr++ != data) {
        printf("Addr[1]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
      data = mexpress_byte(&compare, &val, &av) << 24 | mexpress_byte(&compare, &val, &av) << 16
           | mexpress_byte(&compare, &val, &av) << 8 | mexpress_byte(&compare, &val, &av);
      printf("Addr[2]: %08x, read: %08x, expected: %08x\n", ptr, *(ptr), data);
      ptr++;
      /*if (*ptr++ != data) {
        printf("Addr[2]: %08x, read: %08x, expected: %08x\n", ptr-1, *(ptr-1), data);
        return CNN_FAIL;
      }*/
      printf("Addr[3]: %08x, read: %08x, expected: 00000000\n", ptr, *(ptr));
      ptr++;
      /*if (*ptr++ != 0) {
        printf("Addr[3]: %08x, read: %08x, expected: 00000000\n", ptr-1, *(ptr-1));
        return CNN_FAIL;
      }*/
    }
  }

  return CNN_OK;
}



int cnn_3_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels_3;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    //PR_DEBUG("Loading %d bytes at 0x%x\n", len = *ptr, addr);
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0) {
      //PR_DEBUG("Writing 0x%x to 0x%x\n", *ptr, addr);
      *addr++ = *ptr++; }
  }
  return CNN_OK;
}

int cnn_3_load_bias(void)
{
  // Not used in this network
  return CNN_OK;
}

int cnn_3_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control

  return CNN_OK;
}

int cnn_3_configure(void)
{
   // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50100590) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x0001f8f0; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0xb640d638; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50500590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x0001f8f0; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0xb640d638; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50900590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x0001f8f0; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0xb640d638; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00390) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x0001f8f0; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0xb640d638; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00710) = 0xffffffff; // Mask and processor enables



  return CNN_OK;
}

int cnn_3_start(void)
{
  cnn_3_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_3_unload(uint32_t *out_buf32)
{
  uint8_t *out_buf = (uint8_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;
  int i;

  // Custom unload for this network, layer 0: 8-bit data, shape: (512, 1, 1)
  addr = (volatile uint32_t *) 0x50404000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50404004;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804004;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04004;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004004;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50404008;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804008;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04008;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004008;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5040400c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5080400c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c0400c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5100400c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50404010;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804010;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04010;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004010;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50404014;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804014;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04014;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004014;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50404018;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50804018;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c04018;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x51004018;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5040401c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5080401c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x50c0401c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }
  addr = (volatile uint32_t *) 0x5100401c;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr += 0x2000;
    *out_buf++ = val & 0xff;
    *out_buf++ = (val >> 8) & 0xff;
    *out_buf++ = (val >> 16) & 0xff;
    *out_buf++ = (val >> 24) & 0xff;
  }

  return CNN_OK;
}

int cnn_3_enable(uint32_t clock_source, uint32_t clock_divider)
{
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_3_ISR); // Set CNN complete vector

  return CNN_OK;
}
int cnn_3_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}
